version: '3.8'

services:
  scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: autoria-scraper
    volumes:
      - ./dumps:/app/dumps
      - ./logs:/app/logs
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - SCRAPE_HOUR=${SCRAPE_HOUR}
      - SCRAPE_MINUTE=${SCRAPE_MINUTE}
      - DUMP_HOUR=${DUMP_HOUR}
      - DUMP_MINUTE=${DUMP_MINUTE}
    depends_on:
      - db
    networks:
      - scraper-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: autoria-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - scraper-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: autoria-postgres-data

networks:
  scraper-network:
    name: autoria-network